# -*- coding: utf-8 -*-
"""video_folder_segregator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FO7-IkNTwe2vOjkjmjB8ZfjQY2hS9qy2
"""

import os
import random
import shutil

train_real = '/content/drive/MyDrive/train/real'
train_fake = '/content/drive/MyDrive/train/fake'
test_real = '/content/drive/MyDrive/test/real'
test_fake = '/content/drive/MyDrive/test/fake'

def video_folder_segregator(source_folder, train, test, split_ratio=0.8):

  # Create train and test directories if they don't exist
  if not os.path.exists(train):
      os.makedirs(train)
  if not os.path.exists(test):
      os.makedirs(test)

  # Get a list of all video files in the source folder
  video_files = [f for f in os.listdir(source_folder) if f.endswith(".mp4")]  # Modify the extension if needed

  # Shuffle the list of video files randomly
  random.shuffle(video_files)

  # Split the video files into train and test sets (e.g., 80% train, 20% test)
  split_index = int(len(video_files) * split_ratio)

  train_videos = video_files[:split_index]
  test_videos = video_files[split_index:]

  # Move the selected videos to their respective folders
  for video in train_videos:
      source_path = os.path.join(source_folder, video)
      dest_path = os.path.join(train, video)
      shutil.move(source_path, dest_path)

  for video in test_videos:
      source_path = os.path.join(source_folder, video)
      dest_path = os.path.join(test, video)
      shutil.move(source_path, dest_path)
  print(f"{len(train_videos)} videos moved to train folder.")
  print(f"{len(test_videos)} videos moved to test folder.")

source_folder = '/content/drive/MyDrive/Celeb-df/Celeb-real'
video_folder_segregator(source_folder, train_real, test_real)

source_folder = '/content/drive/MyDrive/Celeb-df/Celeb-synthesis'
video_folder_segregator(source_folder, train_fake, test_fake)

source_folder = '/content/drive/MyDrive/Celeb-df/YouTube-real'
video_folder_segregator(source_folder, train_real, test_real)